#!/bin/bash

# ================= 跨平台系统语言检测 =================
detect_os_lang() {
    local detected="en"
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # 1. macOS: 读取系统 GUI 偏好设置
        if defaults read -g AppleLanguages 2>/dev/null | head -n 5 | grep -qi "zh"; then detected="zh"; fi
    elif [[ "$OSTYPE" == "msys"* || "$OSTYPE" == "cygwin"* || "$OSTYPE" == "win32" ]]; then
        # 2. Windows (Git Bash / MSYS2): 读取注册表
        if reg query "HKCU\Control Panel\International" /v LocaleName 2>/dev/null | grep -qi "zh"; then detected="zh"
        elif [[ "${LANG:-}" == *"zh"* ]]; then detected="zh"; fi
    else
        # 3. Linux / WSL 及其他标准环境
        if [[ "${LANG:-}" == *"zh"* ]]; then detected="zh"; fi
    fi
    echo "$detected"
}

DETECTED_LANG=$(detect_os_lang)

# ================= 多语言字典配置 =================
set_translations() {
    if [ "$EFFECTIVE_LANG" == "en" ]; then
        TXT_WELCOME="👋 Welcome to Git Auto Report"
        TXT_INIT_PROMPT="First run or reconfiguration. Please set your preferences:"
        TXT_ASK_LANG="🌐 0. Select Language (en/zh/auto) [Default: auto]: "
        TXT_ASK_DIR="📁 1. Default parent working directory (e.g. ~/Work): "
        TXT_ASK_GROUP="📊 2. Default report grouping (date or repo) [Default date]: "
        TXT_ASK_ALIGN="🎨 3. Default alignment in concise mode (inline or list) [Default inline]: "
        TXT_SAVED="✅ Configuration saved to"
        TXT_TIP="💡 Tip: You can modify this file anytime, or run './report.sh --init' to reset.\n"
        TXT_UNKNOWN_ARG="Unknown argument:"
        TXT_NO_COMMITS="No matching commits found."
        TXT_GENERATING="Generating report..."
        TXT_WORKSPACE="Workspace:"
        TXT_APPEARANCE="Appearance:"
        TXT_CONCISE="Concise Mode"
        TXT_STD="Standard Markdown"
        TXT_ALIGN_LBL="alignment"
        TXT_INDENT_LBL="indent"
        TXT_CHARS_LBL="chars"
        TXT_REPORT_TITLE="Work Report"
        TXT_GENERATED_BY="Generated by Git Auto Report"
        TXT_DONE="✅ Done!"
        TXT_EXPORT_TIP="(💡 Append --save to export to a file)"
        TXT_EXPORT_SAVED="✅ Done! Result saved to"
    else
        TXT_WELCOME="👋 欢迎使用 Git Auto Report"
        TXT_INIT_PROMPT="首次运行或重新配置，请设置您的偏好参数："
        TXT_ASK_LANG="🌐 0. 请选择语言 (en/zh/auto) [默认: auto]: "
        TXT_ASK_DIR="📁 1. 请输入默认扫描的父级工作目录 (例如 ~/Developer/Work): "
        TXT_ASK_GROUP="📊 2. 默认报告分组方式 (输入 date 或 repo) [默认 date]: "
        TXT_ASK_ALIGN="🎨 3. 简洁模式下的默认对齐方式 (输入 inline 或 list) [默认 inline]: "
        TXT_SAVED="✅ 配置已保存至"
        TXT_TIP="💡 提示：您可以随时修改该文件，或运行 './report.sh --init' 重新设置。\n"
        TXT_UNKNOWN_ARG="未知参数:"
        TXT_NO_COMMITS="未找到符合条件的提交记录。"
        TXT_GENERATING="正在生成汇报..."
        TXT_WORKSPACE="工作区:"
        TXT_APPEARANCE="外观:"
        TXT_CONCISE="简洁模式"
        TXT_STD="标准 Markdown"
        TXT_ALIGN_LBL="对齐"
        TXT_INDENT_LBL="缩进"
        TXT_CHARS_LBL="字符"
        TXT_REPORT_TITLE="工作汇报"
        TXT_GENERATED_BY="由 Git Auto Report 生成"
        TXT_DONE="✅ 完成！"
        TXT_EXPORT_TIP="(💡 若需导出文件，可追加 --save)"
        TXT_EXPORT_SAVED="✅ 完成！结果已保存至"
    fi
}

# ================= 配置文件与初始化 =================
CONFIG_FILE="$HOME/.git-auto-report.conf"

DEFAULT_WORK_DIR="$HOME/Work"
DEFAULT_GROUP_BY="date"
DEFAULT_ALIGN_MODE="inline" 
DEFAULT_LANG_PREF="auto"

# 首次运行或 --init
if [ ! -f "$CONFIG_FILE" ] || [ "$1" == "--init" ]; then
    # 临时生效以便显示引导语言（检测如果是中文则用中文引导，否则英文）
    EFFECTIVE_LANG="$DETECTED_LANG"
    set_translations

    echo "=========================================="
    echo -e "$TXT_WELCOME"
    echo -e "$TXT_INIT_PROMPT"
    echo "=========================================="
    
    read -p "$TXT_ASK_LANG" input_lang
    read -p "$TXT_ASK_DIR" input_dir
    read -p "$TXT_ASK_GROUP" input_group
    read -p "$TXT_ASK_ALIGN" input_align
    
    input_lang="${input_lang:-$DEFAULT_LANG_PREF}"
    input_dir="${input_dir:-$DEFAULT_WORK_DIR}"
    input_group="${input_group:-$DEFAULT_GROUP_BY}"
    input_align="${input_align:-$DEFAULT_ALIGN_MODE}"
    
    # 写入配置文件
    echo "# Git Auto Report 配置文件" > "$CONFIG_FILE"
    echo "LANG_PREF=\"$input_lang\"" >> "$CONFIG_FILE"
    echo "WORK_DIR=\"$input_dir\"" >> "$CONFIG_FILE"
    echo "GROUP_BY=\"$input_group\"" >> "$CONFIG_FILE"
    echo "ALIGN_MODE=\"$input_align\"" >> "$CONFIG_FILE"
    
    # 刷新并提示保存成功
    if [ "$input_lang" == "auto" ]; then EFFECTIVE_LANG="$DETECTED_LANG"; else EFFECTIVE_LANG="$input_lang"; fi
    set_translations
    
    echo -e "\n$TXT_SAVED $CONFIG_FILE。"
    echo -e "$TXT_TIP"
    
    if [ "$1" == "--init" ]; then exit 0; fi
fi

# ================= 加载配置与解析语言 =================
source "$CONFIG_FILE"

LANG_PREF="${LANG_PREF:-$DEFAULT_LANG_PREF}"
ALIGN_MODE="${ALIGN_MODE:-$DEFAULT_ALIGN_MODE}"

# 解析 auto 模式或固定语言
if [ "$LANG_PREF" == "auto" ]; then
    EFFECTIVE_LANG="$DETECTED_LANG"
else
    EFFECTIVE_LANG="$LANG_PREF"
fi

set_translations

# ================= 动态参数配置 =================
AFTER_DATE="midnight"
BEFORE_DATE="now"
SHOW_BRANCH=false
SORT_ASC=false     
CONCISE_MODE=false 
INDENT_SPACES=4    
TEAM_MODE=false    
SAVE_TO_FILE=false 

CUSTOM_USER=$(git config --global user.name 2>/dev/null)
CUSTOM_EMAIL=$(git config --global user.email 2>/dev/null)
TODAY=$(date +%Y-%m-%d)
OUTPUT_FILE=""

# --- 参数解析 ---
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --user) CUSTOM_USER="$2"; shift ;;
        --email) CUSTOM_EMAIL="$2"; shift ;;
        --dir) WORK_DIR="$2"; shift ;;
        --after) AFTER_DATE="$2"; shift ;;
        --before) BEFORE_DATE="$2"; shift ;;
        --by-repo) GROUP_BY="repo" ;;
        --asc) SORT_ASC=true ;;
        --concise) CONCISE_MODE=true ;;
        --align) ALIGN_MODE="$2"; shift ;;
        --indent) INDENT_SPACES="$2"; shift ;;
        --team) TEAM_MODE=true ;;
        --lang) 
            # 命令行强制覆盖语言
            if [ "$2" == "auto" ]; then EFFECTIVE_LANG="$DETECTED_LANG"; else EFFECTIVE_LANG="$2"; fi
            shift ;;
        --save) SAVE_TO_FILE=true; OUTPUT_FILE="WorkReport_${TODAY}.md" ;;
        --out|-o) SAVE_TO_FILE=true; OUTPUT_FILE="$2"; shift ;;
        day) AFTER_DATE="midnight"; BEFORE_DATE="now" ;;
        week) AFTER_DATE="1 week ago"; BEFORE_DATE="now" ;;
        month) AFTER_DATE="1 month ago"; BEFORE_DATE="now" ;;
        --branch) SHOW_BRANCH=true ;;
        *) echo "$TXT_UNKNOWN_ARG $1"; exit 1 ;;
    esac
    shift
done

# 参数解析完后，重新应用语言（防用户传了 --lang）
set_translations

if [[ "$WORK_DIR" == ~* ]]; then WORK_DIR="${WORK_DIR/#\~/$HOME}"; fi

TEMP_LOG_FILE=$(mktemp)
SORTED_FILE=$(mktemp)
trap 'rm -f "$TEMP_LOG_FILE" "$SORTED_FILE"' EXIT INT TERM

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[0;33m'
NC='\033[0m'
DELIM="###"

echo "=========================================="
echo -e "$TXT_GENERATING"
echo -e "$TXT_WORKSPACE ${BLUE}$WORK_DIR${NC}"
echo -e "$TXT_APPEARANCE $(if [ "$CONCISE_MODE" = true ]; then echo "${YELLOW}${TXT_CONCISE} (${ALIGN_MODE} ${TXT_ALIGN_LBL}, ${TXT_INDENT_LBL} ${INDENT_SPACES} ${TXT_CHARS_LBL})${NC}"; else echo "${GREEN}${TXT_STD}${NC}"; fi)"
echo "=========================================="
echo ""

# === 核心日志收集与排版逻辑 ===
find "$WORK_DIR" -type d \( -path "*/node_modules" -o -path "*/.next" -o -path "*/dist" \) -prune -o -name ".git" -type d -print 2>/dev/null | while IFS= read -r gitdir; do
    repo_root=$(dirname "$gitdir")
    cd "$repo_root" || continue
    repo_name=$(basename "$repo_root")

    CMD=(git log)
    if [ -n "$CUSTOM_USER" ]; then CMD+=(--author="$CUSTOM_USER"); fi
    if [ -n "$CUSTOM_EMAIL" ]; then CMD+=(--author="$CUSTOM_EMAIL"); fi
    CMD+=(--after="$AFTER_DATE" --before="$BEFORE_DATE" --no-merges)

    logs=$( "${CMD[@]}" --date=format:'%Y-%m-%d' --pretty=format:"%ai${DELIM}%ad${DELIM}%s${DELIM}%d" 2>/dev/null )
    if [ -n "$logs" ]; then
        echo "$logs" | sed "s/$/${DELIM}$repo_name/" >> "$TEMP_LOG_FILE"
    fi
    cd - > /dev/null
done

if [ ! -s "$TEMP_LOG_FILE" ]; then
    echo "$TXT_NO_COMMITS"
    rm "$TEMP_LOG_FILE" "$SORTED_FILE"
    exit 0
fi

if [ "$GROUP_BY" = "date" ]; then
    if [ "$SORT_ASC" = true ]; then
        awk -F'###' '{print $2 "|" $5 "|" $1 "|" $0}' "$TEMP_LOG_FILE" | sort -t'|' -k1,1 -k2,2 -k3,3 | cut -d'|' -f4- > "$SORTED_FILE"
    else
        awk -F'###' '{print $2 "|" $5 "|" $1 "|" $0}' "$TEMP_LOG_FILE" | sort -t'|' -k1,1r -k2,2 -k3,3r | cut -d'|' -f4- > "$SORTED_FILE"
    fi
else
    if [ "$SORT_ASC" = true ]; then
        awk -F'###' '{print $5 "|" $2 "|" $1 "|" $0}' "$TEMP_LOG_FILE" | sort -t'|' -k1,1 -k2,2 -k3,3 | cut -d'|' -f4- > "$SORTED_FILE"
    else
        awk -F'###' '{print $5 "|" $2 "|" $1 "|" $0}' "$TEMP_LOG_FILE" | sort -t'|' -k1,1 -k2,2r -k3,3r | cut -d'|' -f4- > "$SORTED_FILE"
    fi
fi

# === 使用 AWK 进行规范化分组、提取和排版 ===
FORMATTED_LOGS=$(awk -F'###' -v group_by="$GROUP_BY" -v show_branch="$SHOW_BRANCH" -v concise_mode="$CONCISE_MODE" -v align_mode="$ALIGN_MODE" -v indent_spaces="$INDENT_SPACES" -v lang_pref="$EFFECTIVE_LANG" '
function trim(s) {
    sub(/^[ \t\r\n\v\f]+/, "", s);
    sub(/[ \t\r\n\v\f]+$/, "", s);
    gsub(/[ \t]+/, " ", s);
    return s;
}

BEGIN { 
    last_date = ""; last_repo = ""; type_idx = 1; 
    
    if (lang_pref == "en") {
        L_PROJ = "Project";
        L_FEAT = "Feature"; L_FIX = "Fix"; L_REF = "Refactor";
        L_CHORE = "Chore"; L_DOCS = "Docs"; L_PERF = "Perf"; L_OTHER = "Other";
    } else {
        L_PROJ = "项目";
        L_FEAT = "新功能"; L_FIX = "修复"; L_REF = "重构";
        L_CHORE = "杂项"; L_DOCS = "文档"; L_PERF = "性能"; L_OTHER = "其它";
    }
}

{
    iso_time = $1; date_str = $2; msg = $3; branch = $4; repo = $5;

    type = "other";
    clean_msg = msg;
    if (match(msg, /^[a-zA-Z]+(\([^)]+\))?:\s*/)) {
        prefix_len = RLENGTH;
        prefix = substr(msg, 1, prefix_len);
        clean_msg = substr(msg, prefix_len + 1);
        
        split(prefix, parts, ":");
        type_part = parts[1];
        sub(/\(.*$/, "", type_part); 
        type = tolower(type_part);
    }

    branch_str = (show_branch == "true" && length(branch) > 2) ? " `" branch "`" : "";
    line = clean_msg branch_str;

    if (group_by == "date") {
        if (date_str != last_date) {
            if (last_date != "") print_types();
            printf "### 📅 %s\n\n", date_str;
            printf "【📦 %s】\n", repo;
            last_date = date_str; last_repo = repo;
            reset_types();
        } else if (repo != last_repo) {
            print_types();
            printf "【📦 %s】\n", repo;
            last_repo = repo;
            reset_types();
        }
    } else {
        if (repo != last_repo) {
            if (last_repo != "") print_types();
            printf "## 📦 %s: %s\n\n", L_PROJ, repo;
            printf "### 📅 %s\n\n", date_str;
            last_repo = repo; last_date = date_str;
            reset_types();
        } else if (date_str != last_date) {
            print_types();
            printf "### 📅 %s\n\n", date_str;
            last_date = date_str;
            reset_types();
        }
    }

    if (!(type in type_logs)) {
        group_types[type_idx++] = type;
        type_logs[type] = "";
    }
    type_logs[type] = type_logs[type] line "\n";
}
END { if (last_date != "" || last_repo != "") print_types(); }

function reset_types() {
    for(k in group_types) delete group_types[k];
    for(k in type_logs) delete type_logs[k];
    type_idx = 1;
}

function print_types() {
    if (type_idx == 1) return;

    priority["feat"] = 1; priority["fix"] = 2; priority["refactor"] = 3; priority["perf"] = 4;
    priority["chore"] = 5; priority["docs"] = 6; priority["style"] = 7; priority["test"] = 8;
    priority["build"] = 9; priority["ci"] = 10; priority["other"] = 11;

    n = type_idx - 1;
    for (i = 1; i <= n; i++) {
        for (j = 1; j < n; j++) {
            p1 = (group_types[j] in priority) ? priority[group_types[j]] : 12;
            p2 = (group_types[j+1] in priority) ? priority[group_types[j+1]] : 12;
            if (p1 > p2) { tmp = group_types[j]; group_types[j] = group_types[j+1]; group_types[j+1] = tmp; }
        }
    }

    pad = "";
    for (p = 0; p < indent_spaces; p++) {
        pad = pad " ";
    }

    for (i = 1; i <= n; i++) {
        t = group_types[i];
        n_msgs = split(type_logs[t], msgs, "\n");
        
        if (t == "feat") { label = L_FEAT; cap_type = "✨ Feat (" L_FEAT ")"; }
        else if (t == "fix") { label = L_FIX; cap_type = "🐛 Fix (" L_FIX ")"; }
        else if (t == "refactor") { label = L_REF; cap_type = "♻️ Refactor (" L_REF ")"; }
        else if (t == "chore") { label = L_CHORE; cap_type = "🎫 Chore (" L_CHORE ")"; }
        else if (t == "docs") { label = L_DOCS; cap_type = "📝 Docs (" L_DOCS ")"; }
        else if (t == "perf") { label = L_PERF; cap_type = "⚡️ Perf (" L_PERF ")"; }
        else { label = L_OTHER; cap_type = "🔧 " toupper(substr(t, 1, 1)) substr(t, 2); }

        is_first = 1;

        for (m = 1; m < n_msgs; m++) {
            clean_msg_line = trim(msgs[m]);
            if (length(clean_msg_line) == 0) continue;

            if (concise_mode == "true") {
                if (align_mode == "inline") {
                    if (is_first) { printf "%s:\n", label; is_first = 0; }
                    printf "%s%s\n", pad, clean_msg_line;
                } else {
                    if (is_first) { printf "- **%s**:\n", label; is_first = 0; }
                    printf "  - %s\n", clean_msg_line;
                }
            } else {
                if (is_first) { printf "**%s**\n", cap_type; is_first = 0; }
                printf "- %s\n", clean_msg_line;
            }
        }
    }
    printf "\n";
}
' "$SORTED_FILE")

# === 组装完整文本 ===
FULL_REPORT="# $TXT_REPORT_TITLE ($AFTER_DATE -> $BEFORE_DATE)
$TXT_GENERATED_BY

$FORMATTED_LOGS"

echo "$FULL_REPORT"

echo "=========================================="
if [ "$SAVE_TO_FILE" = true ]; then
    echo "$FULL_REPORT" > "$OUTPUT_FILE"
    echo -e "$TXT_EXPORT_SAVED ${GREEN}$OUTPUT_FILE${NC}"
else
    echo -e "$TXT_DONE ${YELLOW}$TXT_EXPORT_TIP${NC}"
fi